arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.json

# This is to avoid having the generated files in the dart_tool directory.
output-dir: lib/l10n/generated
synthetic-package: false