name: cortdex
description: "Knowledge management tool."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_cortdex:
    path: rust_builder
  flutter_rust_bridge: 2.10.0
  path_provider: ^2.1.5
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0
  http: ^1.2.2
  path: ^1.9.0
  toastification: ^3.0.2
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  equatable: ^2.0.7
  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15
  hooks_riverpod: ^3.0.0-dev.15
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  flutter_animate: ^4.5.2
  share_plus: ^11.0.0
  flutter_slidable: ^4.0.0
  docking: ^1.16.1
  desktop_multi_window: ^0.2.1
  window_manager: ^0.4.3
  tray_manager: ^0.5.0
  window_size: ^0.1.0
  screen_retriever: ^0.2.0
  numberpicker: ^2.1.2
  intl: any
  camera: ^0.11.0+2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  markdown_quill: ^4.3.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  analyzer: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.15
  riverpod_lint: ^3.0.0-dev.15
  go_router_builder: ^2.7.1
  build_runner:
  custom_lint:
  freezed: ^3.0.6
  json_serializable: ^6.9.0

dependency_overrides:
  custom_lint_visitor: 1.0.0+7.3.0
  flutter_quill:
    git:
      url: https://github.com/theniceboy/flutter-quill.git
      ref: fix-flutter-3-32-macos-crash


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  assets:
    - assets/models/sentence-transformers---all-MiniLM-L6-v2/model.safetensors
    - assets/models/sentence-transformers---all-MiniLM-L6-v2/config.json
    - assets/models/sentence-transformers---all-MiniLM-L6-v2/tokenizer.json
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  